# frozen_string_literal: true

module Latchkey
  # Central, explicit configuration object -- see
  # config/initializers/latchkey.rb (generated by `latchkey:install`) for the
  # host-facing side of this. Deliberately a plain attr-accessor object
  # rather than a DSL: every setting is one line to find and one line to
  # override in a test.
  #
  # TODO(v1): flesh out alongside the strategies as they're implemented.
  # Fields anticipated by the design doc (section 9, section 11, section 14):
  #   - challenge                  (a Latchkey::Core::Challenge adapter instance)
  #   - challenge_on               (Array of Symbol form names)
  #   - challenge_when_unavailable (:closed or :open)
  #   - rp_id / rp_name            (WebAuthn relying party identity)
  #   - session lifetime / idle timeout defaults
  class Configuration
    attr_accessor :challenge, :challenge_on, :challenge_when_unavailable

    def initialize
      @challenge = Core::Challenge::Null.new
      @challenge_on = []
      @challenge_when_unavailable = :closed
    end
  end
end
