# frozen_string_literal: true

module AddAuth
  module Rails
    module Migration
      module KeyType
        module_function

        # Resolve when the migration runs, after the host's account table exists.
        # Keep the session keyword for migrations generated by earlier releases.
        def for(connection, table, session: false)
          key = connection.primary_key(table)
          column = connection.columns(table).find { |entry| entry.name == key }
          raise ArgumentError, "AddAuth requires a single integer or UUID primary key on #{table}" unless column
          return :bigint if column.type == :integer && column.limit == 8
          return :integer if column.type == :integer
          return :uuid if column.type == :uuid
          raise ArgumentError, "AddAuth requires an integer or UUID primary key on #{table}"
        end
      end
    end
  end
end
